appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: j5GvmBw1eNLW2QNcvtrgt3awGh5DmaR6OWhfjyVZ2hNc5p0ANoUrrg5M7HPcKr7zw7uSz2hYt5d00q/+va83EifwAYppLNyRpURme7B/4+UdS+uAzOA812X0YZVykd1+Sp5WtEvLLyJcHkpWKCuOPk1p5Moxu7/gN76sJ2w4NUxk5EjWEz9ov1/BGgtHJCd/A8w4rulkckvBddJQC3IYl1ewhckCvZ4n7Fmj2rrat6XQ0yddYnJ2CPwqgSzamc/68RP/4YiwK7LiGccNlzICka/eyAgskzgtgnp34a3eIhaOSUnBdW5MS4qtMyIQnDY4inrY7Lv/8lLvvBzBUICKL0ctDn0O17GYn+f13Y6QfMNUcEiGyMSGy0QECAMlepd1LorertVXjndRipgYLf8vIjZ+3msx1EsXKOwDKhjz7Xp5t+DeXwCdQDPQnwBpa4nj1TcIYy6W5/d92RNtuSBPkWKXKIsKGYAnIvdIaQpV8/J8P9ITPf/J5F8LoJwOku6cFmK+gI/eMNuZ1EOTWNLbM/KA2MzkbjJUKGO9xN8ZrqV3fsspO44rRYs4OVMJvCsqX1QLRSX03cI1Ak+jRIKVIPQJ5WSVyQRIhHJUi4kC3yBRoz8YyyR+HNiV4NIdVGme/2IAALzqBDDn4kIJH9Bw+XVViv01chhRsJTVYt8lLbk=}
